env:
  browser: true
  commonjs: false
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - google
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  max-len:
    - error
    - code: 140
  require-jsdoc:
      - off
