inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.0
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/**'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'config/initializers/canonical_rails.rb'
    - 'config/puma.rb'
    - 'spec/spec_helper.rb'

Layout/AccessModifierIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineArrayLineBreaks:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - tasks/**/*.rb
    - spec/features/*

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*_spec.rb

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 2

Style/StringLiterals:
  EnforcedStyle: single_quotes
