inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require:
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.3.6
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
    - "bin/**"
    - "db/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "config/initializers/canonical_rails.rb"
    - "config/puma.rb"
    - "spec/spec_helper.rb"

Layout/AccessModifierIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineArrayLineBreaks:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - tasks/**/*.rb
    - spec/features/*

RSpec/IndexedLet:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*_spec.rb

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/GuardClause:
  MinBodyLength: 2

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Exclude:
    - config/initializers/*.rb
