version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:8080"  # Map frontend service port to host
    environment:
      API_SERVICE_BACKEND_URL_OPTIONS: "{\"uk\":\"http://backend-uk.tariff.internal:8080\",\"xi\":\"http://backend-xi.tariff.internal:8080\"}"
      AWS_LIGHTSAIL: "true"
      GOVUK_APP_DOMAIN: "localhost"
      GOVUK_WEBSITE_ROOT: "http://localhost/"
      NODE_OPTIONS: "--openssl-legacy-provider"
      RAILS_ENV: "development"
      SECRET_KEY_BASE: "0620b2907b1cee61dbcf5cbbf4125c04bf5db3554c66589d40a9349b5abd5463a40f4a1a8c2db9b07c13715340ee3c94bbc24b1adb3140a20f702e9dc3d4fc0c"
