---
- goods_nomenclature_item_id: '2203000100'
  additional_code: 'X440'
  measure_type_id: '306'
  content_file: 'small_brewers_relief_440'
  overwrite: true
- goods_nomenclature_item_id: '2203000100'
  additional_code: 'X441'
  measure_type_id: '306'
  content_file: 'small_brewers_relief_441'
  overwrite: true
- goods_nomenclature_item_id: '0101210000'
  additional_code: '' # Handle NullObject on Measure#additional_code
  measure_type_id: '350'
  content_file: 'animal_health'
  overwrite: false
- goods_nomenclature_item_id: '0101210000'
  additional_code: '' # Handle NullObject on Measure#additional_code
  measure_type_id: '410'
  content_file: 'vet_control'
  overwrite: true
