name: ci

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TERRAFORM_VERSION: 1.13.5
  PYTHON_VERSION: 3

jobs:
  check-pr-lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0

      - uses: trade-tariff/trade-tariff-tools/.github/actions/check-pr-lines@main
        with:
          threshold: 600
          exclude-paths: |
            db/
            data/
            docs/
            terraform/versions.tf
            config/debride.whitelist
            *.md
            *.lock
            .github

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/cache@v6.1.0
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: ruby/setup-ruby@v1.318.0
        with:
          bundler-cache: true
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-tflint@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-terraform-docs@main
        with:
          terraform_docs_version: 0.22.0
      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-ssh@main
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - run: bundle exec brakeman
      - run: pip install pre-commit
      - run: pre-commit run --all-files --hook-stage pre-commit --show-diff-on-failure
        env:
          RUBOCOP_OPTS: --format github
      - run: pre-commit run --all-files --hook-stage pre-push --show-diff-on-failure

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: ruby/setup-ruby@v1.318.0
        with:
          bundler-cache: true

      - uses: actions/setup-node@v6.4.0
        with:
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: bin/rails assets:precompile

      - name: Run tests
        env:
          PARALLEL_TEST_PROCESSORS: "5"
          SKIP_PARALLEL_TEST_PREPARE: "true"
        run: bundle exec rspec
