name: Deploy to development full

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: read
  id-token: write

jobs:
  deploy-full-stack:
    if: >
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'needs-full-deployment')
    uses: trade-tariff/trade-tariff-tools/.github/workflows/deploy-multi-ecs.yml@main
    with:
      environment: development
      apps: |
        [
          {
            "name": "tariff-frontend",
            "service-names": ["frontend"]
          },
          {
            "name": "tariff-backend",
            "repo": "trade-tariff/trade-tariff-backend",
            "service-names": ["backend-uk", "backend-xi", "worker-uk", "worker-xi"]
          },
          {
            "name": "tariff-admin",
            "repo": "trade-tariff/trade-tariff-admin",
            "service-names": ["admin"]
          },
          {
            "name": "tariff-identity",
            "repo": "trade-tariff/identity",
            "service-names": ["identity"]
          }
        ]
      test-flavour: tariff
    secrets:
      ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
      basic-password: ${{ secrets.BASIC_PASSWORD }}

  axxy:
    needs: deploy-full-stack
    if: >
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'needs-full-deployment')
    uses: trade-tariff/trade-tariff-tools/.github/workflows/axxy-tests.yml@main
    with:
      base-url: https://dev.trade-tariff.service.gov.uk
      admin-url: https://admin.dev.trade-tariff.service.gov.uk
    secrets:
      basic-password: ${{ secrets.BASIC_PASSWORD }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
      ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
