name: Deploy to production

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'Deploy to staging'
    types:
      - completed
    branches:
        - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: trade-tariff/trade-tariff-tools/.github/workflows/deploy-ecs.yml@main
    with:
      app-name: tariff-frontend
      environment: production
    secrets:
      basic-password: ${{ secrets.BASIC_PASSWORD }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
      ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}

  newrelic:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v5
      - id: docker-tag
        run: echo "DOCKER_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - uses: newrelic/deployment-marker-action@v2.6.2
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          region: "EU"
          guid: ${{ secrets.NEW_RELIC_APPLICATION_GUID }}
          version: ${{ steps.docker-tag.outputs.DOCKER_TAG }}
          user: "${{ github.actor }}"
