name: Teardown Preevy environment

on:
  pull_request:
    types: [closed]


permissions:
  contents: read
  id-token: write

concurrency: preevy-${{ github.event.number }}

env:
  AWS_REGION: eu-west-2
  IAM_ROLE_ARN: arn:aws:iam::844815912454:role/GithubActions-ECS-Deployments-Role
  PREEVY_PROFILE_URL: s3://preevy-profile-store?region=eu-west-2

jobs:
  teardown:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: livecycle/preevy-down-action@v1.4.0
        id: preevy_down
        with:
          install: gh-release
          profile-url: ${{ env.PREEVY_PROFILE_URL }}
          args: "--force"
